services:
  backend:
    build: ./backend/app
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend/front-faq
    ports:
      - "3000:3000"
    depends_on:
      - backend
